Repository 2024-EveryCare/backend, pull requests merged in 2024-08, with the labels that each got.

#44 ocr 엔진 테스트
  docker-compose.yml
  src/main/java/com/everycare/backend/global/config/AppConfig.java
Labels: 🔥fix

#45 Feat/#16 복용내역 조회 API 추가
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineRecordController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/MedicineOcrCorrection.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/MedicineRecordRequest.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/MedicineRecordResponse.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/MonthlyMedicineRecordResponse.java
  src/main/java/com/everycare/backend/domain/medicinerecord/entity/MedicineRecord.java
  src/main/java/com/everycare/backend/domain/medicinerecord/repository/MedicineRecordRepository.java
  src/main/java/com/everycare/backend/domain/medicinerecord/service/MedicineRecordService.java
  src/main/java/com/everycare/backend/global/common/SuccessCode.java
  src/main/java/com/everycare/backend/global/config/SecurityConfig.java
  src/main/java/com/everycare/backend/global/controller/LoginController.java
Labels: 🪄feature

#47 스웨거 multipart/form-data 추가
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
Labels: 🪄feature

#48 member_id long으로 변환
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
Labels: 🔥fix

#49 member_id string으로 변환
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
Labels: 🔥fix

#51 corsconfigurations list 수정
  src/main/java/com/everycare/backend/global/config/SecurityConfig.java
Labels: 🔥fix

#53 도커 컨테이너에서 PC의 로컬호스트로 요청보낼 수 있게 수정
  docker-compose.yml
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
Labels: 🔥fix

#57 의약품 삭제 API
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineCorrectionController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineRecordController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/DeleteRecordRequest.java
  src/main/java/com/everycare/backend/domain/medicinerecord/repository/MedicineRecordRepository.java
  src/main/java/com/everycare/backend/domain/medicinerecord/service/MedicineRecordService.java
  src/main/java/com/everycare/backend/global/common/ErrorCode.java
  src/main/java/com/everycare/backend/global/common/SuccessCode.java
Labels: 🪄feature

#60 의약품 검색 API 컨트롤러 분리 / 세션 제외
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineInfoController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineRecordController.java
  src/main/java/com/everycare/backend/global/config/SecurityConfig.java
Labels: 🫧refactor

#63 {memberId} 삭제
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineCorrectionController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineRecordController.java
Labels: 🫧refactor

#64 사진 등록 OCR 클린 코딩
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
  src/main/java/com/everycare/backend/domain/flaskocr/controller/UploadController.java
  src/main/resources/templates/login.html
  src/main/resources/templates/upload.html
Labels: 🫧refactor

#66 findName API 응답 요소 추가
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineInfoController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/FindDrugRequest.java
  src/main/java/com/everycare/backend/domain/medicinerecord/service/MedicineRecordService.java
Labels: 🪄feature

#68 Feat/#59 QR code 이용한 사진 등록
  build.gradle
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
  src/main/java/com/everycare/backend/domain/flaskocr/controller/UploadController.java
  src/main/java/com/everycare/backend/domain/qrcode/service/QrCodeService.java
  src/main/java/com/everycare/backend/domain/qrcode/service/QrCodeServiceImpl.java
  src/main/java/com/everycare/backend/global/config/SecurityConfig.java
  src/main/java/com/everycare/backend/global/config/WebConfig.java
  src/main/java/com/everycare/backend/global/security/JwtAuthenticationFilter.java
  src/main/java/com/everycare/backend/global/security/JwtToken.java
  src/main/java/com/everycare/backend/global/security/JwtTokenFilter.java
  src/main/java/com/everycare/backend/global/security/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 🪄feature

#69 Docker host.docker.internal url 설정
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
Labels: 🫧refactor

#72 회원가입 - password_confirm 추가 / 로그인 - name 반환
  src/main/java/com/everycare/backend/domain/member/controller/MemberController.java
  src/main/java/com/everycare/backend/domain/member/dto/CustomUserDetails.java
  src/main/java/com/everycare/backend/domain/member/dto/LoginResponse.java
  src/main/java/com/everycare/backend/domain/member/dto/SignupRequest.java
  src/main/java/com/everycare/backend/global/common/ErrorCode.java
Labels: 🪄feature

#76 회원정보 조회 API 구현
  src/main/java/com/everycare/backend/domain/member/controller/MemberController.java
  src/main/java/com/everycare/backend/domain/member/dto/MemberInfoResponse.java
  src/main/java/com/everycare/backend/domain/member/service/MemberService.java
  src/main/java/com/everycare/backend/global/common/RestApiResponse.java
  src/main/java/com/everycare/backend/global/common/SuccessCode.java
  src/main/java/com/everycare/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/everycare/backend/global/exception/UnauthorizedAccessException.java
Labels: 🪄feature

#78 모든 복용내역 조회 API 구현
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineRecordController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/MedicineAllRecordResponse.java
  src/main/java/com/everycare/backend/domain/medicinerecord/repository/MedicineRecordRepository.java
  src/main/java/com/everycare/backend/domain/medicinerecord/service/MedicineRecordService.java
  src/main/java/com/everycare/backend/global/common/SuccessCode.java
Labels: 🪄feature

#79 복용내역 조회 응답 수정
  src/main/java/com/everycare/backend/domain/medicinerecord/controller/MedicineRecordController.java
  src/main/java/com/everycare/backend/domain/medicinerecord/dto/MedicineAllRecordResponse.java
  src/main/java/com/everycare/backend/domain/medicinerecord/service/MedicineRecordService.java
  src/main/java/com/everycare/backend/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🫧refactor, 🔥fix

#97 복용내역 모니터링 챗봇 응답 API
  src/main/java/com/everycare/backend/domain/chatbot/controller/ChatGPTController.java
  src/main/java/com/everycare/backend/domain/chatbot/dto/ChatCompletionRequest.java
  src/main/java/com/everycare/backend/domain/chatbot/dto/MedicationStatisticsResponse.java
  src/main/java/com/everycare/backend/domain/chatbot/entity/chatbotentity
  src/main/java/com/everycare/backend/domain/chatbot/repository/chatbot_repository
  src/main/java/com/everycare/backend/domain/chatbot/service/ChatGptClient.java
  src/main/java/com/everycare/backend/domain/chatbot/service/ChatGptService.java
  src/main/java/com/everycare/backend/global/common/SuccessCode.java
Labels: 🪄feature

#99 중복 코드 수정
  src/main/java/com/everycare/backend/domain/chatbot/controller/ChatGPTController.java
  src/main/java/com/everycare/backend/global/common/SuccessCode.java
Labels: 🔥fix

#107 배포 준비
  docker-compose.yml
  src/main/java/com/everycare/backend/domain/flaskocr/controller/FlaskOcrController.java
  src/main/java/com/everycare/backend/global/config/SecurityConfig.java
Labels: 🪄feature

#109 nginx 배포용
  nginx/Dockerfile
  nginx/nginx.conf
Labels: 🪄feature

#111 flaskserver 주석처리
  docker-compose.yml
Labels: 🫧refactor

#113 nginx 디렉토리 구조 변경
  nginx.conf
  nginx/Dockerfile
Labels: 🫧refactor
